In [1]:
import pandas as pd
import os.path

In [37]:
#get the data from file into a table
file = 'C:\\Users\\ischool-user\\Downloads\\co2_hawaii.txt'
col_name = ['site_code', 'year', 'month', 'day', 'hour', 'minute', 'second', 'value', 'value_unc', 'nvalue', 'latitude', 'longitude', 'altitude', 'elevation', 'intake_height', 'instrument', 'qcflag']
data1 = pd.read_table(file, comment='#', delim_whitespace=True, names=col_name)
filter_data=pd.DataFrame(data1[data1['qcflag']!='*..']).reset_index()
max_df=pd.DataFrame(filter_data.groupby('year')[['value']].max()).reset_index()
mean_df=pd.DataFrame(filter_data.groupby('year')[['value']].mean().round(2)).reset_index()
hawaii_df=pd.merge(max_df,mean_df,on='year')
hawaii_df.columns=['year','hawaii_max','hawaii_mean']
hawaii_df['%hawaiichange'] = ((hawaii_df['hawaii_mean'] - (hawaii_df['hawaii_mean'].shift(1) - 1))/(hawaii_df['hawaii_mean'].shift(1) - 1)).fillna(0)
hawaii_df

    year  hawaii_max  hawaii_mean  %hawaiichange
0   1974      333.64       329.55       0.000000
1   1975      334.63       331.39       0.008644
2   1976      336.73       332.07       0.005085
3   1977      337.64       333.85       0.008397
4   1978      338.87       335.43       0.007751
5   1979      340.24       336.69       0.006758
6   1980      342.38       338.83       0.009354
7   1981      343.42       340.09       0.006690
8   1982      345.12       341.32       0.006576
9   1983      346.49       343.18       0.008404
10  1984      348.33       344.74       0.007481
11  1985      349.92       346.07       0.006778
12  1986      351.14       347.30       0.006462
13  1987      352.65       349.27       0.008576
14  1988      354.92       351.58       0.009504
15  1989      356.72       353.20       0.007473
16  1990      358.10       354.47       0.006445
17  1991      360.46       355.67       0.006224
18  1992      360.63       356.43       0.004962
19  1993      361.14       357.16       0.004867
20  1994      362.74       358.91       0.007721
21  1995      365.04       360.86       0.008242
22  1996      366.00       362.67       0.007809
23  1997      368.02       363.71       0.005641
24  1998      370.63       366.70       0.011001
25  1999      372.23       368.31       0.007137
26  2000      373.34       369.58       0.006180
27  2001      375.36       371.07       0.006756
28  2002      376.58       373.29       0.008701
29  2003      380.17       375.83       0.009509
30  2004      381.58       377.66       0.007550
31  2005      383.79       379.96       0.008761
32  2006      385.68       381.89       0.007732
33  2007      387.83       383.86       0.007798
34  2008      390.63       385.52       0.006948
35  2009      391.32       387.42       0.007542
36  2010      394.02       389.84       0.008850
37  2011      395.83       391.66       0.007252
38  2012      397.78       393.87       0.008217
39  2013      400.63       396.47       0.009163
40  2014      402.71       398.71       0.008193
41  2015      404.65       400.87       0.007945
42  2016      409.34       404.25       0.010954

In [38]:
file = 'C:\\Users\\ischool-user\\Downloads\\co2_alaska.txt'
col_name = ['site_code', 'year', 'month', 'day', 'hour', 'minute', 'second', 'value', 'value_unc', 'nvalue', 'latitude', 'longitude', 'altitude', 'elevation', 'intake_height', 'instrument', 'qcflag']
data2 = pd.read_table(file, comment='#', delim_whitespace=True, names=col_name)
filter_data2=pd.DataFrame(data2[data2['qcflag']!='*..']).reset_index()
max_df2=pd.DataFrame(filter_data2.groupby('year')[['value']].max()).reset_index()
mean_df2=pd.DataFrame(filter_data2.groupby('year')[['value']].mean().round(2)).reset_index()
alaska_df=pd.merge(max_df2,mean_df2,on='year')
alaska_df.columns=['year','alaska_max','alaska_mean']
alaska_df['%alaskaChange'] = ((alaska_df['alaska_mean'] - (alaska_df['alaska_mean'].shift(1) - 1))/(alaska_df['alaska_mean'].shift(1) - 1)).fillna(0)
alaska_df

    year  alaska_max  alaska_mean  %alaskaChange
0   1973      339.78       329.22       0.000000
1   1974      340.21       333.78       0.016940
2   1975      343.09       333.62       0.002524
3   1976      338.84       332.97       0.001052
4   1977      342.00       334.95       0.008977
5   1978      343.36       337.20       0.009732
6   1979      344.21       338.36       0.006425
7   1980      347.27       340.42       0.009070
8   1981      348.65       341.96       0.007483
9   1982      351.49       343.08       0.006218
10  1983      353.00       344.22       0.006256
11  1984      353.37       346.41       0.009294
12  1985      354.95       347.11       0.004922
13  1986      355.85       349.13       0.008726
14  1987      356.13       350.13       0.005745
15  1988      360.54       353.47       0.012431
16  1989      364.24       355.25       0.007887
17  1990      363.51       356.04       0.005053
18  1991      370.37       357.89       0.008027
19  1992      365.16       357.87       0.002746
20  1993      364.73       357.53       0.001849
21  1994      369.61       360.40       0.010855
22  1995      372.87       362.45       0.008486
23  1996      371.10       364.30       0.007885
24  1997      372.72       365.25       0.005367
25  1998      376.40       368.04       0.010405
26  1999      376.55       369.75       0.007383
27  2000      379.14       371.22       0.006698
28  2001      379.53       372.99       0.007482
29  2002      381.25       374.54       0.006855
30  2003      387.12       377.90       0.011672
31  2004      385.72       378.68       0.004723
32  2005      388.57       381.40       0.009850
33  2006      390.53       383.63       0.008491
34  2007      392.34       385.29       0.006952
35  2008      396.01       388.12       0.009966
36  2009      396.47       388.50       0.003565
37  2010      399.17       391.21       0.009574
38  2011      403.81       393.28       0.007868
39  2012      403.20       395.55       0.008336
40  2013      408.07       398.31       0.009530
41  2014      409.08       399.83       0.006343
42  2015      409.99       401.91       0.007723
43  2016      412.46       404.94       0.010052

In [40]:
#Merge Hawaii and Alaska dataframes
combined_df=pd.merge(hawaii_df,alaska_df,how='right',on='year')
combined_df

,year,hawaii_max,hawaii_mean,%hawaiichange,alaska_max,alaska_mean,%alaskaChange
0,1974,333.64,329.55,0.000000,340.21,333.78,0.016940
1,1975,334.63,331.39,0.008644,343.09,333.62,0.002524
2,1976,336.73,332.07,0.005085,338.84,332.97,0.001052
3,1977,337.64,333.85,0.008397,342.00,334.95,0.008977
4,1978,338.87,335.43,0.007751,343.36,337.20,0.009732
5,1979,340.24,336.69,0.006758,344.21,338.36,0.006425
6,1980,342.38,338.83,0.009354,347.27,340.42,0.009070
7,1981,343.42,340.09,0.006690,348.65,341.96,0.007483
8,1982,345.12,341.32,0.006576,351.49,343.08,0.006218
9,1983,346.49,343.18,0.008404,353.00,344.22,0.006256
10,1984,348.33,344.74,0.007481,353.37,346.41,0.009294
11,1985,349.92,346.07,0.006778,354.95,347.11,0.004922
12,1986,351.14,347.30,0.006462,355.85,349.13,0.008726
13,1987,352.65,349.27,0.008576,356.13,350.13,0.005745
14,1988,354.92,351.58,0.009504,360.54,353.47,0.012431
15,1989,356.72,353.20,0.007473,364.24,355.25,0.007887
16,1990,358.10,354.47,0.006445,363.51,356.04,0.005053
17,1991,360.46,355.67,0.006224,370.37,357.89,0.008027
18,1992,360.63,356.43,0.004962,365.16,357.87,0.002746
19,1993,361.14,357.16,0.004867,364.73,357.53,0.001849
20,1994,362.74,358.91,0.007721,369.61,360.40,0.010855
21,1995,365.04,360.86,0.008242,372.87,362.45,0.008486
22,1996,366.00,362.67,0.007809,371.10,364.30,0.007885
23,1997,368.02,363.71,0.005641,372.72,365.25,0.005367
24,1998,370.63,366.70,0.011001,376.40,368.04,0.010405
25,1999,372.23,368.31,0.007137,376.55,369.75,0.007383
26,2000,373.34,369.58,0.006180,379.14,371.22,0.006698
27,2001,375.36,371.07,0.006756,379.53,372.99,0.007482
28,2002,376.58,373.29,0.008701,381.25,374.54,0.006855
29,2003,380.17,375.83,0.009509,387.12,377.90,0.011672
30,2004,381.58,377.66,0.007550,385.72,378.68,0.004723
31,2005,383.79,379.96,0.008761,388.57,381.40,0.009850
32,2006,385.68,381.89,0.007732,390.53,383.63,0.008491
33,2007,387.83,383.86,0.007798,392.34,385.29,0.006952
34,2008,390.63,385.52,0.006948,396.01,388.12,0.009966
35,2009,391.32,387.42,0.007542,396.47,388.50,0.003565
36,2010,394.02,389.84,0.008850,399.17,391.21,0.009574
37,2011,395.83,391.66,0.007252,403.81,393.28,0.007868
38,2012,397.78,393.87,0.008217,403.20,395.55,0.008336
39,2013,400.63,396.47,0.009163,408.07,398.31,0.009530
40,2014,402.71,398.71,0.008193,409.08,399.83,0.006343
41,2015,404.65,400.87,0.007945,409.99,401.91,0.007723
42,2016,409.34,404.25,0.010954,412.46,404.94,0.010052
43,1973,NaN,NaN,NaN,339.78,329.22,0.000000

In [42]:
combined_df.set_index('year', inplace=True)
combined_df

,hawaii_max,hawaii_mean,%hawaiichange,alaska_max,alaska_mean,%alaskaChange
year,,,,,,
1974,333.64,329.55,0.000000,340.21,333.78,0.016940
1975,334.63,331.39,0.008644,343.09,333.62,0.002524
1976,336.73,332.07,0.005085,338.84,332.97,0.001052
1977,337.64,333.85,0.008397,342.00,334.95,0.008977
1978,338.87,335.43,0.007751,343.36,337.20,0.009732
1979,340.24,336.69,0.006758,344.21,338.36,0.006425
1980,342.38,338.83,0.009354,347.27,340.42,0.009070
1981,343.42,340.09,0.006690,348.65,341.96,0.007483
1982,345.12,341.32,0.006576,351.49,343.08,0.006218
1983,346.49,343.18,0.008404,353.00,344.22,0.006256
1984,348.33,344.74,0.007481,353.37,346.41,0.009294
1985,349.92,346.07,0.006778,354.95,347.11,0.004922
1986,351.14,347.30,0.006462,355.85,349.13,0.008726
1987,352.65,349.27,0.008576,356.13,350.13,0.005745
1988,354.92,351.58,0.009504,360.54,353.47,0.012431
1989,356.72,353.20,0.007473,364.24,355.25,0.007887
1990,358.10,354.47,0.006445,363.51,356.04,0.005053
1991,360.46,355.67,0.006224,370.37,357.89,0.008027
1992,360.63,356.43,0.004962,365.16,357.87,0.002746
1993,361.14,357.16,0.004867,364.73,357.53,0.001849
1994,362.74,358.91,0.007721,369.61,360.40,0.010855
1995,365.04,360.86,0.008242,372.87,362.45,0.008486
1996,366.00,362.67,0.007809,371.10,364.30,0.007885
1997,368.02,363.71,0.005641,372.72,365.25,0.005367
1998,370.63,366.70,0.011001,376.40,368.04,0.010405
1999,372.23,368.31,0.007137,376.55,369.75,0.007383
2000,373.34,369.58,0.006180,379.14,371.22,0.006698
2001,375.36,371.07,0.006756,379.53,372.99,0.007482
2002,376.58,373.29,0.008701,381.25,374.54,0.006855
2003,380.17,375.83,0.009509,387.12,377.90,0.011672
2004,381.58,377.66,0.007550,385.72,378.68,0.004723
2005,383.79,379.96,0.008761,388.57,381.40,0.009850
2006,385.68,381.89,0.007732,390.53,383.63,0.008491
2007,387.83,383.86,0.007798,392.34,385.29,0.006952
2008,390.63,385.52,0.006948,396.01,388.12,0.009966
2009,391.32,387.42,0.007542,396.47,388.50,0.003565
2010,394.02,389.84,0.008850,399.17,391.21,0.009574
2011,395.83,391.66,0.007252,403.81,393.28,0.007868
2012,397.78,393.87,0.008217,403.20,395.55,0.008336
2013,400.63,396.47,0.009163,408.07,398.31,0.009530
2014,402.71,398.71,0.008193,409.08,399.83,0.006343
2015,404.65,400.87,0.007945,409.99,401.91,0.007723
2016,409.34,404.25,0.010954,412.46,404.94,0.010052
1973,NaN,NaN,NaN,339.78,329.22,0.000000

In [44]:
hawaii_perc_mean=combined_df['%hawaiichange'].mean()
alaska_perc_mean=combined_df['%alaskaChange'].mean()
hawaii_perc_mean

0.007489174113321184

In [45]:
alaska_perc_mean

0.007441314950571743

In [46]:
#writing dataframe to output file
#writing the final output to file
base_filename = 'Output.txt'
with open(os.path.join('C:\\Users\\ischool-user\\Downloads', base_filename),'w') as outfile:
    combined_df.to_string(outfile)